from fastapi import APIRouter, HTTPException, Query
from typing import Optional
import logging
import fastf1
import pandas as pd
from utils.gp_codes import resolve_gp_name

logger = logging.getLogger(__name__)
router = APIRouter()

@router.get("/data/{dataset}")
def get_universal_data(
    dataset: str,
    year: int = Query(...),
    prix: str = Query(...),
    session: str = Query(...),
    driver: Optional[str] = Query(None)
):
    """
    Polymorphic extraction endpoint for FastF1 data. 
    Accepts dataset: [telemetry, laps, weather, messages, track_status]
    """
    valid_datasets = ['telemetry', 'laps', 'weather', 'messages', 'track_status']
    if dataset not in valid_datasets:
        raise HTTPException(status_code=400, detail=f"Invalid dataset '{dataset}'. Valid options: {valid_datasets}")

    try:
        # Load the Core Session — resolve GP code (e.g. "AUS" → "Australian Grand Prix")
        gp_name = resolve_gp_name(prix)
        f1_session = fastf1.get_session(year, gp_name, session)
        
        # Load data based on requested dataset to optimize parsing time
        if dataset in ['weather']:
            f1_session.load(weather=True, telemetry=False, laps=False, messages=False)
        elif dataset in ['messages', 'track_status']:
            f1_session.load(weather=False, telemetry=False, laps=False, messages=True)
        else:
            # Default heavy load for telemetry or laps
            f1_session.load(weather=False, telemetry=True, laps=True, messages=False)

        data_df = pd.DataFrame()

        # Extract specific DataFrame
        if dataset == 'weather':
            data_df = f1_session.weather_data
        
        elif dataset == 'messages':
            data_df = f1_session.race_control_messages
            
        elif dataset == 'track_status':
            data_df = f1_session.track_status
            
        elif dataset == 'laps':
            if driver:
                data_df = f1_session.laps.pick_drivers(driver)
            else:
                data_df = f1_session.laps
                
        elif dataset == 'telemetry':
            if not driver:
                raise HTTPException(status_code=400, detail="Driver is required for telemetry datasets.")
            fastest_lap = f1_session.laps.pick_drivers(driver).pick_fastest()
            if getattr(fastest_lap, 'empty', True):
                raise ValueError(f"No fastest lap found for driver {driver}")
            
            # Extract raw unaligned telemetry
            raw_tel = fastest_lap.get_telemetry()
            
            import numpy as np
            
            # Sub-select specific columns to keep the payload clean
            cols_to_keep = ['Time', 'Distance', 'Speed', 'RPM', 'nGear', 'Throttle', 'Brake', 'DRS', 'X', 'Y', 'Z', 'DriverAhead']
            available_cols = [c for c in cols_to_keep if c in raw_tel.columns]
            data_df = raw_tel[available_cols].copy()

            # --- MATH ENGINE: 3D G-Force Array Extrapolation ---
            
            # 1. dt in seconds (Required for all derivatives)
            dt = data_df['Time'].dt.total_seconds().diff()
            
            # 2. Longitudinal G (Acceleration / Braking)
            v_ms = data_df['Speed'] / 3.6
            a_lon = v_ms.diff() / dt
            data_df['Lon_G'] = a_lon / 9.81
            
            # 3. Lateral G (Cornering Load)
            if 'X' in data_df.columns and 'Y' in data_df.columns:
                # Calculate trajectory angle theta
                theta = np.arctan2(data_df['Y'].diff(), data_df['X'].diff())
                # Unwrap to prevent 360-degree modulus jumps from causing infinite angular velocity
                theta_unwrapped = np.unwrap(theta.fillna(0))
                # Angular velocity omega
                omega = pd.Series(theta_unwrapped).diff() / dt
                # Centripetal Acceleration = v * omega
                a_lat = omega * v_ms
                data_df['Lat_G'] = a_lat / 9.81
            else:
                data_df['Lat_G'] = 0.0

            # 4. Vertical G (Elevation Compression Changes)
            if 'Z' in data_df.columns:
                # Vertical velocity
                v_z = data_df['Z'].diff() / dt
                # Vertical acceleration
                a_z = v_z.diff() / dt
                data_df['Vert_G'] = a_z / 9.81
            else:
                data_df['Vert_G'] = 0.0

            # Clean infinites and NaNs generated by calculus derivatives (especially on element 0)
            data_df = data_df.replace([np.inf, -np.inf], np.nan).fillna(0)
            
            # Cast Timedeltas to seconds for JSON serialization
            if 'Time' in data_df.columns:
                 data_df['Time'] = data_df['Time'].dt.total_seconds()
            if 'SessionTime' in data_df.columns:
                 data_df['SessionTime'] = data_df['SessionTime'].dt.total_seconds()

        # CRITICAL RULE: JSON Serialization constraints
        # 1. Fill NaN with 0 or empty string depending on column type
        # 2. Convert Timedelta objects to strings or floats (FastF1 relies heavily on Timedeltas)
        
        # Fill numeric NaNs with 0
        import numpy as np
        data_df = data_df.select_dtypes(include=[np.number]).fillna(0).combine_first(data_df)
        # Fill object/string NaNs with 'NaN' strings to prevent UI crashes if completely bare
        data_df = data_df.fillna("N/A")

        # Convert remaining exotic types (Timedeltas)
        for col in data_df.columns:
            if pd.api.types.is_timedelta64_dtype(data_df[col]):
                data_df[col] = data_df[col].dt.total_seconds()
            elif pd.api.types.is_datetime64_any_dtype(data_df[col]):
                data_df[col] = data_df[col].dt.strftime('%Y-%m-%d %H:%M:%S')

        # Convert to final list of dicts for JSON
        raw_json_records = data_df.to_dict('records')

        return {
            "status": "success",
            "dataset": dataset,
            "count": len(raw_json_records),
            "data": raw_json_records
        }

    except Exception as e:
        logger.error(f"API Error in Universal Data Layer ({dataset}): {str(e)}")
        raise HTTPException(status_code=500, detail=str(e))
